version: "3.8"
networks:
  backend:
    driver: "bridge"
services:
  postgres:
    image: postgres:13-alpine
    command: ["postgres", "-c", "fsync=false", "-c", "full_page_writes=off"]
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - "5432:5432"
    networks:
      - backend
  redis:
    image: redis:7.0.8-alpine
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - 'redis:/data'
    networks:
      - backend
  sidekiq:
    build:
      context: .
      dockerfile: app.Dockerfile
    command: bundle exec sidekiq
    environment:
      RAILS_ENV: 'development'
      REDIS_URL: 'redis://redis:6379/1'
    depends_on:
      - app
      - postgres
      - redis
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - backend
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    command: bash -c "bundle exec puma -C config/puma.rb"
    environment:
      RAILS_ENV: development
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    networks:
      - backend
  nginx:
    build:
      context: .
      dockerfile: ./nginx.Dockerfile
    depends_on:
      - app
    ports:
      - 80:80
    networks:
      - backend
volumes:
  redis:
  postgres: